課題：WebアプリからのDB利用
kekosh/sinatra-memo-app pull request #2
Opened 2021-12-23 15:29 UTC by kekosh

前課題で作成したアプリケーションを元にデータをDBに格納する仕様に変更しました。

2021-12-30 04:55 UTC, komagata requested changes

2021-12-30 04:55 UTC, komagata commented on README.md
> +$git clone https://github.com/kekosh/sinatra-memo-app.git
```suggestion
$ git clone https://github.com/kekosh/sinatra-memo-app.git
```

2021-12-30 04:55 UTC, komagata commented on README.md
> +$bundle exec ruby app.rb
```suggestion
$ bundle exec ruby app.rb
```

2021-12-30 04:55 UTC, komagata commented on views/edit.erb
> +</body>
最終行に改行が無いようです〜

2021-12-30 04:55 UTC, komagata commented on views/layout.erb
> +  </html>
最終行に改行がないのと、インデントがおかしいかもです〜

2021-12-30 04:55 UTC, komagata commented on Gemfile
> +gem 'webrick'
webrickって必須かな？と思いました。なくても動く気がします〜

2021-12-30 04:55 UTC, komagata commented on app.rb
> +require 'Rack'
```suggestion
require 'rack'
```

こうかも？

2021-12-30 04:59 UTC, komagata commented on DB/ddl.sql
> +CREATE TABLE memos (
DDLとサンプルデータのSQLが付属してるの良いですね👍

2021-12-30 13:30 UTC, kekosh commented on README.md
> +$git clone https://github.com/kekosh/sinatra-memo-app.git
指摘いただいたとおり、$とコマンドの間に半角スペースを追加しました。

2021-12-30 13:40 UTC, kekosh commented on README.md
> +$git clone https://github.com/kekosh/sinatra-memo-app.git
指摘いただいた箇所を修正しました。

2021-12-30 13:40 UTC, kekosh commented on README.md
> +$bundle exec ruby app.rb
指摘いただいた箇所を修正しました。

コミット番号；db55e62

2021-12-30 13:41 UTC, kekosh commented on views/edit.erb
> +</body>
指摘いただいた箇所を修正しました。

コミット番号；db55e62

2021-12-30 13:42 UTC, kekosh commented on views/layout.erb
> +  </html>
指摘いただいた箇所を修正しました。

コミット番号；db55e62

2021-12-30 15:02 UTC, kekosh commented on app.rb
> +require 'Rack'
指摘いただいた箇所を修正しました。

コミット番号；db55e62

2021-12-30 15:04 UTC, kekosh commented on Gemfile
> +gem 'webrick'
なんで記載したのか不明ですか、webrickをGemfileから削除しました。

コミット番号：815f161

2021-12-30 15:38 UTC, kekosh commented on Gemfile
> +gem 'webrick'
`webrick`をGemfileから除いて実行してみましたが、下記のエラーとなり正常に動きませんでした。

```
/Users/kekosh/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1755:in `detect_rack_handler': Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)
```

2021-12-30 15:40 UTC, kekosh commented on DB/ddl.sql
> +CREATE TABLE memos (
ありがとうございます。
自分がレビューするならあった方がいいだろうな、と思ったことがGoodな評価をいただけて
うれしいです。

2021-12-31 04:25 UTC, komagata commented on Gemfile
> +gem 'webrick'
@kekosh ほんとですね、すみません、知りませんでした〜。

2021-12-31 04:27 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-12-31 04:27 UTC, komagata commented on Gemfile
> +# gem "rails"
基本的にgitで管理しているものにコメントアウトしてコードを残すということは不要なので消しちゃって良いと思います〜

2021-12-31 14:28 UTC, kekosh commented on Gemfile
> +# gem "rails"
消し忘れでしたので不要なコメントアウトを削除しました。

2021-12-31 14:29 UTC, merged